name: HA Validation Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Hassfest Validation

    steps:
      - uses: actions/checkout@v4

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@1.0.0
        with:
          args: custom_components/meteocat_community_edition
        with:
          args: --integration-path custom_components/meteocat_community_edition
